-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    email character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Movie"
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    "Rating" smallint,
    review text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user_Movie"
(
    user_id integer NOT NULL,
    "Movie_Rating" smallint
);

CREATE TABLE IF NOT EXISTS public."user_Movie"
(
    user_id integer NOT NULL,
    "Movie_review" text
);

CREATE TABLE IF NOT EXISTS public."Group"
(
    id integer NOT NULL,
    "name of group" character varying(50) NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Group favourites"
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Group_user"
(
    "Group_id" integer NOT NULL,
    user_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."User favourites"
(
    name character varying(50) NOT NULL,
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user_User favourites"
(
    user_id integer NOT NULL,
    "User favourites_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Group Invites"
(
    id_groupinvite integer,
    id_user_request integer,
    id_user_invite integer,
    id_group integer
);

CREATE TABLE IF NOT EXISTS public."Group_Group favourites"
(
    "Group_id" integer NOT NULL,
    "Group favourites_id" integer NOT NULL
);

ALTER TABLE IF EXISTS public."user_Movie"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user_Movie"
    ADD FOREIGN KEY ("Movie_Rating")
    REFERENCES public."Movie" ("Rating") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user_Movie"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user_Movie"
    ADD FOREIGN KEY ("Movie_review")
    REFERENCES public."Movie" (review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Group"
    ADD FOREIGN KEY (id)
    REFERENCES public."Group Invites" (id_groupinvite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Group_user"
    ADD FOREIGN KEY ("Group_id")
    REFERENCES public."Group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Group_user"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user_User favourites"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user_User favourites"
    ADD FOREIGN KEY ("User favourites_id")
    REFERENCES public."User favourites" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Group Invites"
    ADD FOREIGN KEY (id_user_request)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Group_Group favourites"
    ADD FOREIGN KEY ("Group_id")
    REFERENCES public."Group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Group_Group favourites"
    ADD FOREIGN KEY ("Group favourites_id")
    REFERENCES public."Group favourites" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;